// Regenerate with `cargo test -p emailterminator export_bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	storeStatus: () => __TAURI_INVOKE<StoreStatus>("store_status"),
};

/* Types */
/**  What S17 and S16 show about local data at rest. */
export type StoreStatus = { state: "open"; keyBackend: string; cipherVersion: string } | 
/**  The key no longer opens the database (S16, "database key missing"). */
{ state: "locked" } | { state: "failed"; message: string };

